workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Create and set iOS deployment target in Podfile
        script: |
          # Create Podfile if it does not exist
          if [ ! -f "ios/Podfile" ]; then
            echo "Creating Podfile..."
            echo "platform :ios, '13.0'" > ios/Podfile
            echo "use_frameworks!" >> ios/Podfile
            echo "use_modular_headers!" >> ios/Podfile
            echo "" >> ios/Podfile
            echo "target 'Runner' do" >> ios/Podfile
            echo "  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))" >> ios/Podfile
            echo "end" >> ios/Podfile
          fi
          # Ensure pods are installed
          cd ios
          pod install
          cd ..

      - name: Clean Flutter and get dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
